name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  checkout-code:
    name: Checkout Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

  lint-backend:
    name: Lint Backend
    runs-on: ubuntu-latest
    needs: checkout-code
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Make gradlew Executable
        run:
          chmod +x gradlew
      - name: Lint Backend Code
        run:
          ./gradlew check
  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    needs: lint-backend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Make gradlew Executable
        run:
          chmod +x gradlew
      - name: Run Backend Tests
        run:
          ./gradlew test
